angeluz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include(('aplications.home.urls', 'home'), namespace='home')),
    path('blog/', include(('aplications.blog.urls', 'blog'), namespace='blog')),
    path('faqs/', include(('aplications.faq.urls', 'faq'), namespace='faq')),
    path('servicios/', include(('aplications.service.urls', 'service'), namespace='service')),
    path('contacto/', include(('aplications.contact.urls', 'contact'), namespace='contact')),
    path('newsletter/', include(('aplications.newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('users/', include(('aplications.users.urls', 'users'), namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

aplications/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog_app'

urlpatterns = [
    path(
        '', 
        views.EntradaListView.as_view(),
        name='entradas'
    ),
    path(
        'categoria/<slug>/', 
        views.CategoryEntradaListView.as_view(),
        name='categoria'
    ),
    path(
        'tag/<slug>/', 
        views.TagEntradaListView.as_view(),
        name='tag'
    ),
    path(
        'entrada/<slug>/', 
        views.EntradaDetalleView.as_view(),
        name='entrada'
    ),
]

aplications/blog/models.py
from datetime import datetime
from django.db import models
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField

from aplications.users.models import User
# Create your models here.

from .managers import EntradaManager, CategoriaEntradaManager, TagManager, ComentarioManager

class CategoriaEntrada(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    slug = models.SlugField(max_length=100, verbose_name='Slug', unique=True)
    active = models.BooleanField(verbose_name='Activo', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    objects = CategoriaEntradaManager()

    class Meta:
        verbose_name = 'categoría de entrada'
        verbose_name_plural = 'categorías de entradas'
        ordering = ['-created']

    def __str__(self):
        return self.name
    
    
class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='Nombre')
    slug = models.SlugField(max_length=100, verbose_name='Slug')
    active = models.BooleanField(verbose_name='Activo', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    objects = TagManager()

    class Meta:
        verbose_name = 'tag'
        verbose_name_plural = 'tags'
        ordering = ['-created']

    def __str__(self):
        return self.name

class Entrada(models.Model):
    categoria = models.ForeignKey(CategoriaEntrada, verbose_name='Categoría', on_delete=models.CASCADE, blank=True, null=True)
    tags = models.ManyToManyField(Tag, verbose_name='Tags')
    title = models.CharField(max_length=200, verbose_name='Título')
    slug = models.SlugField(max_length=200, verbose_name='Slug', unique=True)
    autor = models.ForeignKey(User, verbose_name='Autor', on_delete=models.CASCADE)
    description = RichTextUploadingField('Contenido')
    summary = models.TextField(verbose_name='Resumen', blank=True, null=True)
    image = models.ImageField(verbose_name='Imagen', upload_to='blog')
    active = models.BooleanField(verbose_name='Activo', default=True)
    destacado = models.BooleanField(verbose_name='Destacado', default=False)
    showHome = models.BooleanField(verbose_name='Mostrar en Home', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    objects = EntradaManager()

    class Meta:
        verbose_name = 'entrada'
        verbose_name_plural = 'entradas'
        ordering = ['-created']

    def save(self, *args, **kawrgs):
        if self.slug == slugify(self.title):
            time = datetime.now().microsecond
            self.slug = self.slug + '-' + str(time)
        super(Entrada, self).save(*args, **kawrgs)

    def __str__(self):
        return self.title
    


class Comentario(models.Model):
    entrada = models.ForeignKey(Entrada, verbose_name='Entrada', on_delete=models.CASCADE)
    autor = models.ForeignKey(User, verbose_name='Autor', on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Comentario')
    active = models.BooleanField(verbose_name='Activo', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')


    objects = ComentarioManager()

    class Meta:
        verbose_name = 'comentario'
        verbose_name_plural = 'comentarios'
        ordering = ['-created']

    def __str__(self):
        return self.autor.name

aplications/blog/forms.py
from django import forms


from .models import Comentario


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = (
            'comment',
        )

        widgets = {
            'comment': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'placeholder':'Escribe tu comentario...'}),
        }

aplications/blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy

# Create your views here.
from django.views.generic.edit import FormMixin
from django.views.generic import ListView, DetailView

from aplications.home.models import Background


from .forms import ComentarioForm
from .models import Entrada, CategoriaEntrada, Tag, Comentario

class EntradaListView(ListView):
    template_name = "blog/list.html"
    queryset = Entrada.objects.entradas_home()
    paginate_by = 6
    context_object_name = 'entradas'


    def get_context_data(self, **kwargs):
        context = super(EntradaListView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page(3)
        context['categorias'] = CategoriaEntrada.objects.categorias_activas()
        context['tags'] = Tag.objects.tags_activos()
        context['entradas_destcadas'] = Entrada.objects.entradas_destacadas()
        return context


class EntradaDetalleView(FormMixin, DetailView):
    template_name = "blog/detail.html"
    model = Entrada
    context_object_name = "entrada"
    form_class = ComentarioForm
    
    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super(EntradaDetalleView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page('3')
        context['entradas'] = Entrada.objects.entradas_destacadas()	
        context['categorias'] = CategoriaEntrada.objects.categorias_activas()
        context['comentarios'] = Comentario.objects.comentarios_entrada(self.kwargs['slug'])
        context['form'] = self.get_form()
        return context
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        

    def form_valid(self, form):
        form.instance.entrada = self.object
        form.instance.autor = self.request.user
        form.save()
        return super(EntradaDetalleView, self).form_valid(form)
    

class CategoryEntradaListView(ListView):
    template_name = "blog/list.html"
    paginate_by = 6
    context_object_name = "entradas"
    

    def get_queryset(self):
        return Entrada.objects.entradas_categoria(self.kwargs['slug'])
    

    def get_context_data(self, **kwargs):
        context = super(CategoryEntradaListView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page('3')
        context['categoria'] = CategoriaEntrada.objects.get(slug=self.kwargs['slug'])
        context['categorias'] = CategoriaEntrada.objects.categorias_activas()
        context['tags'] = Tag.objects.tags_activos()
        context['entradas_destcadas'] = Entrada.objects.entradas_destacadas()
        return context
    

class TagEntradaListView(ListView):
    template_name = "blog/list.html"
    paginate_by = 6
    context_object_name = "entradas"
    

    def get_queryset(self):
        return Entrada.objects.entradas_tag(self.kwargs['slug'])
    

    def get_context_data(self, **kwargs):
        context = super(TagEntradaListView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page('3')
        context['tag'] = Tag.objects.get(slug=self.kwargs['slug'])
        context['categorias'] = CategoriaEntrada.objects.categorias_activas()
        context['tags'] = Tag.objects.tags_activos()
        context['entradas_destcadas'] = Entrada.objects.entradas_destacadas()
        return context

templates/modulos/blog/detalle_v1.html
<div class="main">
    <section class="module-small">
      <div class="container">
        <div class="row">
          <div class="col-sm-4 col-md-3 sidebar">
            <div class="widget">
              <h5 class="widget-title font-alt">Categorias</h5>
              <ul class="icon-list">
                {% for category in categorias %}
                  <li><a href="{% url 'blog_app:categoria' category.slug %}">{{category}} - {{ category.entrada_set.all|length }}</a></li>
                {% endfor %}
              </ul>
            </div>
            <div class="widget">
              <h5 class="widget-title font-alt">Entradas importantes</h5>
              <ul class="widget-posts">
                {% for entrada in entradas %}
                  <li class="clearfix">
                    <div class="widget-posts-image"><a href="{% url 'blog_app:entrada' entrada.slug %}"><img src="{{entrada.image.url}}" alt="Post Thumbnail"/></a></div>
                    <div class="widget-posts-body">
                      <div class="widget-posts-title"><a href="{% url 'blog_app:entrada' entrada.slug %}">{{ entrada.title }}</a></div>
                      <div class="widget-posts-meta">{{ entrada.created|date:"d M" }}</div>
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <div class="widget">
              <h5 class="widget-title font-alt">Tag</h5>
              <div class="tags font-serif">
                {% for tag in entrada.tags.all %}
                  <a href="{% url 'blog_app:tag' tag.slug %}" rel="tag">{{tag}}</a>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="col-sm-8 col-sm-offset-1">
            <div class="post">
              <div class="post-thumbnail"><img src="{{entrada.image.url}}" alt="Blog Featured Image"/></div>
              <div class="post-header font-alt">
                <h1 class="post-title">{{ entrada.title }}</h1>
                <div class="post-meta">By&nbsp;<span>{{ entrada.autor.name }}</span>  {{  entrada.created|date:"d M Y"  }} 
                    <a href="{% url 'blog_app:categoria' entrada.categoria.slug %}">{{entrada.categoria}} </a>
                </div>
              </div>
              <div class="post-entry">
                {{ entrada.description|safe }}
              </div>
            </div>
            {% if not comentarios|length < 1 %}
            <div class="comments">
              <h4 class="comment-title font-alt">Total comentarios: {{ comentarios|length }}</h4>
              {% for comentario in comentarios %}
                <div class="comment clearfix">
                    <div class="comment-content clearfix">
                    <div class="comment-author font-alt"><span>{{ comentario.autor.get_short_name }}</span></div>
                    <div class="comment-body">
                        <p>{{ comentario.comment }}</p>
                    </div>
                    <div class="comment-meta font-alt">{{ comentario.created }}
                    </div>
                    </div>
                </div>
              {% endfor %}
            </div>
            {% endif %}
            {% if user.is_authenticated %}
            <div class="comment-form">
              <h4 class="comment-form-title font-alt">Add your comment</h4>
              <form method="post">
                {% csrf_token %}
                <!-- <div class="form-group">
                 
                  <input id="id_autor" name="autor" value="{{ user.name }}" type="hidden" />
                  <input id="id_entrada" name="entrada" value="{{ entrada.slug }}" type="hidden" />
                </div>
                <div class="form-group">
                  <textarea class="form-control" id="id_comment" name="comment" rows="4" placeholder="Comment"></textarea>
                </div>  -->

                {{form.as_p}}
                <button class="btn btn-round btn-d" type="submit">Comentar</button>
              </form>
            </div>
            {% else %}
              <h3>Debe iniciar sesión si quieres comentar</h3>
            {% endif %}
          </div>
          
        </div>
      </div>
    </section>
  </div>

templates/modulos/blog/v1.html
<section class="module" id="news">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          
            {% if section.section == "3" %}
              <h2 class="module-title font-alt">{{ section.title }}</h2>
              <div class="module-subtitle font-serif">{{ section.content|safe }}</div>
            {% endif %}
        </div>
      </div>
      <div class="row multi-columns-row post-columns">
        {% for entrada in entradas %}
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="post mb-20">
                    <div class="post-thumbnail"><a href="#"><img src="{{entrada.image.url}} " alt="Blog-post Thumbnail"/></a></div>
                <div class="post-header font-alt">
                <h2 class="post-title"><a href="#">{{ entrada.title }}</a></h2>
                <div class="post-meta">By&nbsp;<span>{{entrada.autor.name}}</span>&nbsp;| {{ entrada.created|date:"d M Y" }} 
                </div>
                </div>
                <div class="post-entry">
                  {{ entrada.summary|safe|truncatechars:250  }}
                </div>
                <div class="post-more"><a class="more-link" href="#">Ver más</a></div>
            </div>
            </div>
        {% endfor %}  
      </div>
      <a  style="position: absolute; left: 47%;" href="{% url 'blog_app:entradas' %}">Ver más</a>
    </div>
  </section>

templates/modulos/blog/v2.html
<div class="module">
    <div class="container">
        <div class="row" style="text-align: center;margin-bottom: 4rem;position: relative;">
            {% if categoria %}
                <h2>
                    Categoria
                </h2>
                <h3>
                    {{ categoria|upper }}
                </h3>
                {% endif %}
            {% if tag %}
                <h2>
                    Tag
                </h2>
                <h3>
                    {{ tag|upper }}
                </h3>
            {% endif %}
        </div>
        <div class="row">
            <div class="col-sm-4 col-md-3 sidebar">
                {% if categorias %}
                    <div class="widget">
                        <h5 class="widget-title font-alt">Categorias</h5>
                        <ul class="icon-list">
                            {% for category in categorias %}
                            <li><a href="{% url 'blog_app:categoria' category.slug %}">{{category}} - {{ category.entrada_set.all|length }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% if entradas_destcadas %}
                <div class="widget">
                    <h5 class="widget-title font-alt">Entradas importantes</h5>
                    <ul class="widget-posts">
                        {% for entrada in entradas_destcadas %}
                        <li class="clearfix">
                            <div class="widget-posts-image"><a href="{% url 'blog_app:entrada' entrada.slug %}"><img
                                        src="{{entrada.image.url}}" alt="Post Thumbnail" /></a></div>
                            <div class="widget-posts-body">
                                <div class="widget-posts-title"><a href="{% url 'blog_app:entrada' entrada.slug %}">{{ entrada.title }}</a></div>
                                <div class="widget-posts-meta">{{ entrada.created|date:"d M" }}</div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
                {% if tags %}
                    <div class="widget">
                        <h5 class="widget-title font-alt">Tags</h5>
                        <div class="tags font-serif">
                            {% for tag in tags %}
                            <a href="{% url 'blog_app:tag' tag.slug %}" rel="tag">{{tag}}</a>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="col-sm-8 col-sm-offset-1"></div>
            <div class="row multi-columns-row post-columns">
                {% if entradas %}
                    {% for entrada in entradas %}
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <div class="post">
                            <div class="post-thumbnail"><a href="{% url 'blog_app:entrada' entrada.slug %}"><img
                                        src="{{entrada.image.url}}" alt="Blog-post Thumbnail" /></a></div>
                            <div class="post-header font-alt">
                                <h2 class="post-title"><a href="{% url 'blog_app:entrada' entrada.slug %}">{{ entrada.title }}</a></h2>
                                <div class="post-meta">By&nbsp;<a href="#">{{ entrada.autor.name }}</a>&nbsp; {{ entrada.created|date:"d M Y" }}
                                </div>
                            </div>
                            <div class="post-entry">
                                {{ entrada.summary|safe|truncatechars:250 }}
                            </div>
                            <div class="post-more"><a class="more-link" href="{% url 'blog_app:entrada' entrada.slug %}">Ver más</a></div>
                        </div>
                    </div>
                    {% endfor %}
                {% else %}
                    <div class="col-sm-6 col-md-4 col-lg-4">
                        <h2>No hay entradas</h2>
                    </div>
                {% endif %}
            </div>
            {% if entradas|length > 5 %}
                <div class="pagination font-alt">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i></a>
                    {% endif %}
                    {% for page in paginator.page_range %}
                        {% if page_obj.number == page %}
                            <a class="active" href="?page={{ page }}">{{ page }}</a>
                        {% else %}
                            <a href="?page={{ page }}">{{ page }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-angle-right"></i></a>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>
</div>
</section>