angeluz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include(('aplications.home.urls', 'home'), namespace='home')),
    path('blog/', include(('aplications.blog.urls', 'blog'), namespace='blog')),
    path('faqs/', include(('aplications.faq.urls', 'faq'), namespace='faq')),
    path('servicios/', include(('aplications.service.urls', 'service'), namespace='service')),
    path('contacto/', include(('aplications.contact.urls', 'contact'), namespace='contact')),
    path('newsletter/', include(('aplications.newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('users/', include(('aplications.users.urls', 'users'), namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

aplications/contact/urls.py
from django.urls import path
from . import views

app_name = 'contact_app'

urlpatterns = [
    path('', views.AddContactMessageView.as_view(), name='contact'),
    path('success/', views.SuccessView.as_view(), name='success'),
    # Agrega aquí más rutas de URL según tus necesidades
]

aplications/contact/models.py
from django.db import models

# Create your models here.
class Contacto(models.Model):
    name = models.CharField(max_length=200, verbose_name='Nombre')
    email = models.EmailField(verbose_name='Correo electrónico')
    message = models.TextField(verbose_name='Mensaje')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    pending = models.BooleanField(verbose_name='Pendiente', default=True)
    reviewed = models.BooleanField(verbose_name='Revisado', default=False)

    def reviewed_true(self):
        if self.pending == True:
            self.reviewed = False
        elif self.pending == False:
            self.reviewed = True
        self.save()

    class Meta:
        verbose_name = 'contacto'
        verbose_name_plural = 'contactos'
        ordering = ['-created']

    def __str__(self):
        return self.name

aplications/contact/forms.py
from django import forms


from .models import Contacto


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = (
            'name',
            'email',
            'message',
        )
        

aplications/contact/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.template.loader import render_to_string

# Create your views here.
from django.views.generic import CreateView, TemplateView
from django.conf import settings

from aplications.home.models import Background

from .forms import ContactForm

class AddContactMessageView(CreateView):
    form_class = ContactForm
    success_url = reverse_lazy('contact_app:success')
    template_name = 'contacto/contact.html'

    def get_context_data(self, **kwargs):
        context = super(AddContactMessageView, self).get_context_data(**kwargs)
        context['background'] = context['background'] = Background.objects.background_page("5")
        context['info'] = {
            "title": "Contáctanos"
        }
        
        return context
    
    def form_valid(self, form):
        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        
        template = 'contact_email_template.html'
        context = {
            'nombre': name,
            'correo': email,
            'mensaje': message
        }
            
        subject = 'Nuevo mensaje de contacto'
        message_to_send = render_to_string(template, context)
        try:
            send_mail(
                subject,
                '',
                settings.DEFAULT_FROM_EMAIL,
                [settings.DEFAULT_FROM_EMAIL],
                fail_silently=False,
                html_message=message_to_send
            )
        except Exception as e:
            print(e)
            return self.form_invalid(form)
        return super(AddContactMessageView, self).form_valid(form)


class SuccessView(TemplateView):
    template_name = 'contacto/success.html'
    def get_context_data(self, **kwargs):
        context = super(SuccessView, self).get_context_data(**kwargs)
        context['background'] = context['background'] = Background.objects.background_page("5")

        return context

templates/modulos/contact/success.html
<section class="module" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt">
            <div class="alert alert-success" role="alert">
               <strong>El mensaje ha sido enviado con éxito</strong> 
              </div>
          </h2>
          <div class="module-subtitle font-serif"></div>
        </div>
      </div>
      <div class="row">
        
        <div class="col-sm-6 col-sm-offset-3">
            <p>
                <a href="{{ main_url }}">
                <button class="btn btn-success btn-circle btn-block" type="button">
                        Volver al inicio
                    </button>
                </a>
              </p>
          <div class="ajax-response font-alt" id="contactFormResponse"></div>
        </div>
      </div>
    </div>
  </section>

templates/modulos/contact/v1.html
<section class="module" id="contact">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt">{{ info.title }}</h2>
          <div class="module-subtitle font-serif"></div>
        </div>
      </div>
      <div class="row">
        
        <div class="col-sm-6 col-sm-offset-3">
          
          {% if user.is_authenticated %}
          <form  role="form" method="post" action="{% url 'contact_app:contact' %}">
            {% csrf_token %}
                <div class="form-group">
                  
                  <input class="form-control" type="hidden" id="id_name" name="name" value="{{user.name}}" placeholder="Your Name*" required="required" data-validation-required-message="Please enter your name."/>
                 
                </div>
                <div class="form-group">
                  
                  <input class="form-control" type="hidden" id="id_email" name="email" value="{{user.email}}" placeholder="Your Email*" required="required" data-validation-required-message="Please enter your email address."/>
             
                </div>
                <div class="form-group">
                  <textarea class="form-control" rows="7" id="id_message" name="message" placeholder="Your Message*" required="required" data-validation-required-message="Please enter your message."></textarea>
                  <p class="help-block text-danger"></p>
                </div>
                <div class="text-center">
                  <button class="btn btn-block btn-round btn-d"  type="submit">Enviar</button>
                </div>
              </form>
          {% else %}

          
            <form  role="form" method="post" action="{% url 'contact_app:contact' %}">
              {% csrf_token %}
              <div class="form-group">
                <label class="sr-only" for="name">Name</label>
                <input class="form-control" type="text" id="id_name" name="name" placeholder="Your Name*" required="required" data-validation-required-message="Please enter your name."/>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <label class="sr-only" for="email">Email</label>
                <input class="form-control" type="email" id="id_email" name="email" placeholder="Your Email*" required="required" data-validation-required-message="Please enter your email address."/>
                <p class="help-block text-danger"></p>
              </div>
              <div class="form-group">
                <textarea class="form-control" rows="7" id="id_message" name="message" placeholder="Your Message*" required="required" data-validation-required-message="Please enter your message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
              <div class="text-center">
                <button class="btn btn-block btn-round btn-d"  type="submit">Enviar</button>
              </div>
            </form>
          {% endif %}
          <div class="ajax-response font-alt" id="contactFormResponse"></div>
        </div>
      </div>
    </div>
  </section>



    