angeluz/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include(('aplications.home.urls', 'home'), namespace='home')),
    path('blog/', include(('aplications.blog.urls', 'blog'), namespace='blog')),
    path('faqs/', include(('aplications.faq.urls', 'faq'), namespace='faq')),
    path('servicios/', include(('aplications.service.urls', 'service'), namespace='service')),
    path('contacto/', include(('aplications.contact.urls', 'contact'), namespace='contact')),
    path('newsletter/', include(('aplications.newsletter.urls', 'newsletter'), namespace='newsletter')),
    path('users/', include(('aplications.users.urls', 'users'), namespace='users')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] 



urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    })
]

aplications/service/urls.py
from django.urls import path

from . import views

app_name = 'service_app'

urlpatterns = [
    path(
        '', 
        views.ServicesListView.as_view(),
        name='servicio'
    ),
    path(
        '<slug:slug>/', 
        views.ServiceDetailView.as_view(),
        name='servicio_detail'
    ),
]

aplications/service/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

from .managers import ServiceManager

class Service(models.Model):
    title = models.CharField(max_length=200, verbose_name='Título')
    subtitle = models.CharField(max_length=200, verbose_name='Subtítulo', blank=True, null=True)
    summary = models.TextField(verbose_name='Resumen', blank=True, null=True)
    description = RichTextUploadingField('Contenido')
    slug = models.SlugField(verbose_name='Slug', unique=True)
    icon = models.CharField(max_length=200, verbose_name='Icono',blank=True, null=True , help_text='Usar una clase de Fontawesome, consultar los iconos en https://fontawesome.com/search?m=free&o=r, icon que se verá en la home')
    image = models.ImageField(verbose_name='Imagen', upload_to='services', blank=True, null=True)
    active = models.BooleanField(verbose_name='Activo', default=True)
    destacado = models.BooleanField(verbose_name='Destacado', default=False)
    showHome = models.BooleanField(verbose_name='Mostrar en Home', default=True)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')

    objects = ServiceManager()

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'
        ordering = ['-created']

    def __str__(self):
        return self.title
    
    def save(self, *args, **kawrgs):
        if self.slug == slugify(self.title):
            time = datetime.now().microsecond
            self.slug = self.slug + '-' + str(time)
        super(Service, self).save(*args, **kawrgs)

aplications/service/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView

from aplications.home.models import Background, Pagina

from .models import Service


class ServicesListView(ListView):
    template_name = "services/list.html"
    queryset = Service.objects.activos()
    context_object_name = "services"
    

    def get_context_data(self, **kwargs):
        context = super(ServicesListView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page('4')
        context['info'] = Pagina.objects.filter(codigo='1')
        context['design1'] = 'sections/services/fragments/design_v1.html'
        context['design2'] = 'sections/services/fragments/design_v2.html'
        return context
    
class ServiceDetailView(DetailView):
    template_name = "services/detalle_v1.html"
    model = Service
    context_object_name = "servicio"

    def get_context_data(self, **kwargs):
        context = super(ServiceDetailView, self).get_context_data(**kwargs)
        context['background'] = Background.objects.background_page('4')
        return context
    

templates/modulos/service/detalle_v1.html
<div class="main">
    <section class="module-small">
      <div class="container">
        <div class="row">
          
          <div class="col-sm-8 col-sm-offset-2">
            <div class="post">
              <div class="post-thumbnail"><img src="{{servicio.image.url}}" alt="Blog Featured Image"/></div>
              <div class="post-header font-alt">
                <h1 class="post-title">{{ servicio.title }}</h1>
                
              </div>
              <div class="post-entry">
                {{ servicio.description|safe }}
              </div>
            </div>
            <div class="container">
              <div class="row">

                
                <a class="btn btn-success btn-circle col-sm-2 col-sm-offset-0 col-xs-10 col-xs-offset-1" target="_blank" href="https://api.whatsapp.com/send/?phone={{ whatsapp }}&text={{ whatsapp_text }}&type=phone_number">Contáctanos</a>
                <span class="col-sm-4"></span>
                <a class="btn btn-g btn-circle col-sm-2 col-sm-offset-0 col-xs-10 col-xs-offset-1 mt-xs-10"  href="{% url 'service_app:servicio' %}">Volver</a>
              </div>
             
            </div>
          </div>
        </div>

    </div>
</section>
  
    
  </div>

templates/modulos/service/v1.html
<section class="module" style="padding-top: 0;">
    <div class="container">
      <ul class="works-grid works-grid-3 works-grid-gut works-hover-d" id="works-grid">
        {% for servicio in services %}            
            <li class="work-item">
                <a href="{% url 'service_app:servicio_detail' servicio.slug %}">
                    <div class="work-image"><img src="{{ servicio.image.url }}" alt="Portfolio Item"/></div>
                    <div class="work-caption font-alt">
                    <h3 class="work-title">{{ servicio.title }}</h3>
                    <div class="work-descr">{{ servicio.summary }}</div>
                    </div>
                </a>
            </li>
        {% endfor %}
      </ul>
        <a target="_blank" class="btn btn-success btn-circle col-sm-2 col-sm-offset-5 mt-40 col-xs-10 col-xs-offset-1" href="https://api.whatsapp.com/send/?phone={{ whatsapp }}&text={{ whatsapp_text }}&type=phone_number">Contáctanos</a>
    </div>
  </section>

templates/modulos/service/v2.html
<section class="module">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <ul class="filter font-alt" id="filters">
            <li><a class="current wow fadeInUp" href="#" data-filter="*">All</a></li>
            <li><a class="wow fadeInUp" href="#" data-filter=".illustration" data-wow-delay="0.2s">Illustration</a></li>
            <li><a class="wow fadeInUp" href="#" data-filter=".marketing" data-wow-delay="0.4s">Marketing</a></li>
            <li><a class="wow fadeInUp" href="#" data-filter=".photography" data-wow-delay="0.6s">Photography</a></li>
            <li><a class="wow fadeInUp" href="#" data-filter=".webdesign" data-wow-delay="0.6s">Web Design</a></li>
          </ul>
        </div>
      </div>
      <ul class="works-grid works-grid-3 works-grid-gut works-hover-d" id="works-grid">
        <li class="work-item illustration webdesign"><a href="portfolio_single_featured_image1.html">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio1.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Corporate Identity</h3>
              <div class="work-descr">Illustration</div>
            </div></a></li>
        <li class="work-item marketing photography"><a href="portfolio_single_featured_image2.html">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio2.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Bag MockUp</h3>
              <div class="work-descr">Marketing</div>
            </div></a></li>
        <li class="work-item illustration photography"><a href="portfolio_single_featured_slider1.html">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio3.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Disk Cover</h3>
              <div class="work-descr">Illustration</div>
            </div></a></li>
        <li class="work-item marketing photography"><a href="portfolio_single_featured_slider2.htmll">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio4.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Business Card</h3>
              <div class="work-descr">Photography</div>
            </div></a></li>
        <li class="work-item illustration webdesign"><a href="portfolio_single_featured_video1.html">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio5.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Web Design</h3>
              <div class="work-descr">Webdesign</div>
            </div></a></li>
        <li class="work-item marketing webdesign"><a href="portfolio_single_featured_video2.html">
            <div class="work-image"><img src="assets/images/portfolio/grid-portfolio6.jpg" alt="Portfolio Item"/></div>
            <div class="work-caption font-alt">
              <h3 class="work-title">Paper clip</h3>
              <div class="work-descr">Marketing</div>
            </div></a></li>
      </ul>
    </div>
  </section>